#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

# 1) Python command detection
# Prefer active virtualenv interpreter when available, then fallback to system python3/python.
if [ -n "${VIRTUAL_ENV:-}" ] && [ -x "${VIRTUAL_ENV}/bin/python3" ]; then
  PYTHON="${VIRTUAL_ENV}/bin/python3"
elif [ -n "${VIRTUAL_ENV:-}" ] && [ -x "${VIRTUAL_ENV}/bin/python" ]; then
  PYTHON="${VIRTUAL_ENV}/bin/python"
elif command -v python3 >/dev/null 2>&1; then
  PYTHON="$(command -v python3)"
elif command -v python >/dev/null 2>&1; then
  PYTHON="$(command -v python)"
else
  echo "ERROR: python3/python not found" >&2
  exit 1
fi

PIP="$PYTHON -m pip"
RUNS_DIR="$ROOT_DIR/runs"
mkdir -p "$RUNS_DIR"

# 2) srcレイアウトのimport対策（暫定）
# - まず editable install を試す（失敗しても続行）
# - それでも不安定な場合は PYTHONPATH=src を付与
PYTHONPATH_EXPORT=""
if [ -d "$ROOT_DIR/src" ]; then
  PYTHONPATH_EXPORT="$ROOT_DIR/src"
fi

if [ -f "$ROOT_DIR/pyproject.toml" ]; then
  set +e
  "$PYTHON" -m pip install -e . >/dev/null 2>&1
  set -e
fi

# 3) env.sh を生成（SSOT）
cat > "$ROOT_DIR/scripts/env.sh" <<ENV
# Auto-generated by scripts/preflight.sh
export ROOT_DIR="$ROOT_DIR"
export RUNS_DIR="$RUNS_DIR"
export PYTHON="$PYTHON"
export PIP="$PIP"
ENV

if [ -n "$PYTHONPATH_EXPORT" ]; then
  echo "export PYTHONPATH=\"$PYTHONPATH_EXPORT\"" >> "$ROOT_DIR/scripts/env.sh"
fi

chmod +x "$ROOT_DIR/scripts/env.sh"

echo "preflight: PYTHON=$PYTHON"
if [ -n "$PYTHONPATH_EXPORT" ]; then
  echo "preflight: PYTHONPATH=$PYTHONPATH_EXPORT"
fi
